name: Go

on:
  create:
    tags:
      - v*
  push:
    branches: [ ci-test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test
      run: make test
    - name: Set environment variables
      run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build
      run: ./scripts/build.py
